version: '3.8'

services:
  app:
    build: .
    container_name: focus_tracker_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

  prometheus_server:
    image: prom/prometheus:v2.53.0
    container_name: prometheus_server
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana_dashboard:
    image: grafana/grafana:11.1.0
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      # THIS IS THE FIX: We are pointing Grafana to a new, fresh volume.
      - grafana-storage-v2:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

# THIS IS THE FIX: We define the new, fresh volume here.
volumes:
  grafana-storage-v2: {}